name: Release
run-name: Releasing, triggered by ${{github.actor}}

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE: jakethecoder95/codeless-versioning

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Echo the tag
        run: echo "The pushed tag is ${{ steps.previoustag.outputs.tag }}"

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ env.DOCKERHUB_USERNAME }}
#           password: ${{ env.DOCKERHUB_TOKEN }}

#       - name: Build and Push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ steps.semvers.outputs.minor }}-${{ steps.vars.outputs.sha_short}}


