name: Release
run-name: Releasing, triggered by ${{github.actor}}

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE: jakethecoder95/codeless-versioning

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: currenttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Search latest semver Image
        uses: tinact/docker.image-retag@1.0.3
        with:
          image_name: ${{ env.IMAGE }}
          image_old_tag: ${{ steps.currenttag.outputs.tag }}-${{ steps.vars.outputs.sha_short}}
          image_new_tag: ${{ steps.currenttag.outputs.tag }}
          registry: registry.hub.docker.com
          registry_username: ${{ env.DOCKERHUB_USERNAME }}
          registry_password: ${{ env.DOCKERHUB_TOKEN }}
